language: minimal

env:
  - IMAGE_NAME=foxcapades/alpine-oracle

services:
- docker

script:
- echo docker build -t ${IMAGE_NAME}:${TRAVIS_BRANCH}
- docker build -t ${IMAGE_NAME}:${TRAVIS_BRANCH}
- echo docker tag ${IMAGE_NAME}:${TRAVIS_BRANCH} ${IMAGE_NAME}:latest
- docker tag ${IMAGE_NAME}:${TRAVIS_BRANCH} ${IMAGE_NAME}:latest

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true
